---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
      fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'github01main'
        git config --global user.email 'shiwook_github_01@hotmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy